{
 "title": "Big Dashboard",
 "tags": [ "demo" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory / CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.request_status.code_302.count, 10), 20), 'cpu')"
    },
    {
     "target": "alias(statsd.fakesite.counters.session_start.desktop.count, 'memory')"
    }
   ]
  },
  {
   "title": "logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), 2), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(apps.fakesite.web_server_01.counters.requests.count, 1), '1h'), 2), 'logins (-1 hour)')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.4)"
    }
   ]
  },
  {
   "title": "Sign ups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Sign outs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "apps.backend.backend_04.counters.requests.count"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.7)"
    }
   ]
  },
  {
   "title": "server requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(movingAverage(scaleToSeconds(apps.fakesite.*.counters.requests.count, 1), 2), 2)"
    }
   ]
  },
  {
   "title": "Logouts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.8)"
    }
   ]
  },
  {
   "title": "Support calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(apps.backend.backend_03.counters.requests.count, 0.3)"
    }
   ]
  },
  {
   "title": "Google hits",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.2)"
    }
   ]
  },
  {
   "title": "Google hits",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(apps.backend.backend_01.counters.requests.count, 0.2)"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(summarize(statsd.fakesite.timers.ads_timer.*, '4min', 'avg'), 4)"
    }
   ]
  }
 ]
}