#!/bin/sh

set -e

[ -f /etc/sysconfig/logdisplayplatform-server ] && . /etc/sysconfig/logdisplayplatform-server

startLogDisplayPlatform() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start logdisplayplatform-server.service
	elif [ -x /etc/init.d/logdisplayplatform-server ] ; then
		/etc/init.d/logdisplayplatform-server start
	elif [ -x /etc/rc.d/init.d/logdisplayplatform-server ] ; then
		/etc/rc.d/init.d/logdisplayplatform-server start
	fi
}

stopLogDisplayPlatform() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop logdisplayplatform-server.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/logdisplayplatform-service ] ; then
		/etc/init.d/logdisplayplatform-service stop
	elif [ -x /etc/rc.d/init.d/logdisplayplatform-service ] ; then
		/etc/rc.d/init.d/logdisplayplatform-service stop
	fi
}


# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$GRAFANA_USER" ] && GRAFANA_USER="logdisplayplatform"
	[ -z "$GRAFANA_GROUP" ] && GRAFANA_GROUP="logdisplayplatform"
	if ! getent group "$GRAFANA_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$GRAFANA_GROUP"
	fi
	if ! getent passwd "$GRAFANA_USER" > /dev/null 2>&1 ; then
    useradd -r -g logdisplayplatform -d /usr/share/logdisplayplatform -s /sbin/nologin \
    -c "logdisplayplatform user" logdisplayplatform
	fi

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/logdisplayplatform/conf/sample.ini $CONF_FILE
    cp /usr/share/logdisplayplatform/conf/ldap.toml /etc/logdisplayplatform/ldap.toml
  fi

  if [ ! -f $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/logdisplayplatform/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/logdisplayplatform/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi 

 	# Set user permissions on /var/log/logdisplayplatform, /var/lib/logdisplayplatform
	mkdir -p /var/log/logdisplayplatform /var/lib/logdisplayplatform
	chown -R $GRAFANA_USER:$GRAFANA_GROUP /var/log/logdisplayplatform /var/lib/logdisplayplatform
	chmod 755 /var/log/logdisplayplatform /var/lib/logdisplayplatform

	# configuration files should not be modifiable by logdisplayplatform user, as this can be a security issue
	chown -Rh root:$GRAFANA_GROUP /etc/logdisplayplatform/*
	chmod 755 /etc/logdisplayplatform
	find /etc/logdisplayplatform -type f -exec chmod 640 {} ';'
	find /etc/logdisplayplatform -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure logdisplayplatform to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable logdisplayplatform-server.service"
    echo "### You can start logdisplayplatform-server by executing"
    echo " sudo /bin/systemctl start logdisplayplatform-server.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting logdisplayplatform-server by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add logdisplayplatform-server"
    echo "### In order to start logdisplayplatform-server, execute"
    echo " sudo service logdisplayplatform-server start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopLogDisplayPlatform
    startLogDisplayPlatform
  fi
fi
