#!/bin/sh

set -e

echo "POSTTRANS: Running script"

[ -f /etc/sysconfig/logdisplayplatform-server ] && . /etc/sysconfig/logdisplayplatform-server

# copy config files if missing
if [ ! -f /etc/logdisplayplatform/logdisplayplatform.ini ]; then
  echo "POSTTRANS: Config file not found"

  if [ -f /etc/logdisplayplatform/logdisplayplatform.ini.rpmsave ]; then
    echo "POSTTRANS: /etc/logdisplayplatform/logdisplayplatform.ini.rpmsave config file found."
    mv /etc/logdisplayplatform/logdisplayplatform.ini.rpmsave /etc/logdisplayplatform/logdisplayplatform.ini
    echo "POSTTRANS: /etc/logdisplayplatform/logdisplayplatform.ini restored"

    if [ -f /etc/logdisplayplatform/ldap.toml.rpmsave ]; then
      echo "POSTTRANS: /etc/logdisplayplatform/ldap.toml.rpmsave found"
      mv /etc/logdisplayplatform/ldap.toml.rpmsave /etc/logdisplayplatform/ldap.toml
      echo "POSTTRANS: /etc/logdisplayplatform/ldap.toml restored"
    fi

    echo "POSTTRANS: Restoring config file permissions"
    chown -Rh root:$GRAFANA_GROUP /etc/logdisplayplatform/*
    chmod 755 /etc/logdisplayplatform
    find /etc/logdisplayplatform -type f -exec chmod 640 {} ';'
    find /etc/logdisplayplatform -type d -exec chmod 755 {} ';'
  fi
fi


